name: Publish on Bever Marketplace CI

on:
  push:
    branches: release

jobs:
  main:
    uses: BeverCRM/Workflow-Build-Release-Upload-Update/.github/workflows/build-release-upload-update-rw.yml@master
    secrets: inherit
    with:
      control-title: Drag and Drop Grid
      control-youtube-video-url: https://www.youtube.com/watch?v=jvDp9eG5RCo
      control-tags: Drag and Drop, Grid